// Re-export all types from the new modular structure
// This file maintains backward compatibility for existing imports
export type { CategoryLarge, CategoryMedium, CategorySmall } from "./types/category"
export type { Material, MaterialCostEntry, MaterialStock } from "./types/material"
export type { PackagingItem, PackagingCostEntry, PackagingStock } from "./types/packaging"
export type { ShippingMethod, LogisticsCostEntry } from "./types/shipping"
export type { LaborRole, LaborCostEntry } from "./types/labor"
export type { Equipment, EquipmentAllocationEntry } from "./types/equipment"
export type { Fee, FeeCostEntry } from "./types/fee"
export type { ProductSizeVariant, Product, ProductStatus, OptionPreset, ProductStock } from "./types/product"
export type { OutsourcingCostEntry, DevelopmentCostEntry, ElectricityCostEntry } from "./types/cost-entry"
export type { StockAlertSetting } from "./types/stock"
export type { AuditLogMetadata, ChangeSummary, AuditFilters, AuditLog } from "./types/audit"
export type { ExchangeRate } from "./types/exchange-rate"
export type { TimeRecord, TimeRecordLap } from "./types/time-record"
export type { ProcessTemplate, ProductProcess } from "./types/process"
export type { AppData } from "./types/app-data"
export { emptyAppData } from "./types/app-data"
export { sampleAppData, defaultAppData } from "./types/sample-data"
